name: Build and Upload new version
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 */6 *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: chmod +x ./bin/typst && ./bin/typst compile --font-path fonts cv.typ
      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "cv.pdf"
          tag: "v${{ github.run_number }}"
